// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwCWNZEvu3sHqZJKgRm3e-kzvYcQqpqp0',
    appId: '1:168253128406:web:a735af303fb9663751d377',
    messagingSenderId: '168253128406',
    projectId: 'trainapp-prod',
    authDomain: 'trainapp-prod.firebaseapp.com',
    storageBucket: 'trainapp-prod.firebasestorage.app',
    measurementId: 'G-22P09X9N92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq6KROTf1c4pe70S5XCL5atdwN-0wTI34',
    appId: '1:168253128406:android:3490e4ff7dde9b1851d377',
    messagingSenderId: '168253128406',
    projectId: 'trainapp-prod',
    storageBucket: 'trainapp-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEU0rObF1LkvA6fb-HhGMGRkQ5RuZnkY0',
    appId: '1:168253128406:ios:cb2d9cc82ef1398051d377',
    messagingSenderId: '168253128406',
    projectId: 'trainapp-prod',
    storageBucket: 'trainapp-prod.firebasestorage.app',
    iosClientId: '168253128406-gp1gobhia4bq773fobs95o618e8jn1c7.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainappMobile',
  );
}
